### ISSUE TITLE
Not receiving messages from chatbot

### ISSUE THREAD

**Issue by titan99855** [lhchavez/gtalkchat#98] opened 2011-11-17 20:48 UTC
Some friends and I use a chatbot to group chat with Gtalk. The issue with the Gchat phone app is that it does not receive messages from the chatbot contact, but it sends messages just fine. It will on occasion receive a few messages, but most of the time it does not. I can add users to the bot for the sake of reproducing the problem.

**Comment by lhchavez** [comment] 2011-11-17 20:57
interesting, i will check the problem later today. by the way, because of
server capacity constraints, the server can only hold connections for up to
two hours of inactivity. do you think that is the cause of the problem? if
not, i'll provide you with a test email so you can add it to the group and
investigate further.
On Nov 17, 2011 12:48 PM, "titan99855" <
reply@reply.github.com>
wrote:

**Comment by titan99855** [comment] 2011-11-17 21:11
I do not think the inactivity timeout is causing the problem because the chat can be active and then I jump on the phone and it will not receive. I would be glad to add your test email to the chatbot.

**Comment by titan99855** [comment] 2011-11-28 19:55
Any updates on this?

**Comment by limitedmage** [comment] 2012-04-16 03:06
Fixed in 1.5

**Closed as completed by limitedmage** 2012-04-16 03:06 UTC
