### ISSUE TITLE
[Requests] Incoming messages highlight & thread removal from Recent section

### ISSUE THREAD

**Issue by vanquish83** [lhchavez/gtalkchat#121] opened 2012-04-19 08:47 UTC
Would be possible to temporarily sort the online contact list putting on top contacts who just send a message? 

Some time i miss some messages because:
- in the "online contacts" i just don't see the number of incoming message because the contact is the bottom of the list (i've to remember to manually to scroll the list).
- in the "recent contacts" some times the number of incoming message is hard to read.  For example, if a contact has an avatar with dark colour, the incoming message number is unreadeable.

Another nice thing would be the option to remove a single thread from "recent contact" section.

**Comment by limitedmage** [comment] 2012-04-19 08:57
> Would be possible to temporarily sort the online contact list putting on top contacts who just send a message?

Our design centers around three lists: online, sorted by status, all, sorted by name, and recent, sorted by time. Your most recent messages are already easily available -- on the recent list. Is there a reason you'd rather have them on the online list instead?

> If a contact has an avatar with dark colour, the incoming message number is unreadeable.

The number is white-on-black, there shouldn't be any problems with readability, unless you mean the circle itself, in which case the text should still be visible.. Do you have any screenshots showing this?

> Another nice thing would be the option to remove a single thread from "recent contact" section.

This is a dupe of #80, we're already planning that :)

**Comment by limitedmage** [comment] 2012-05-11 07:10
Closing this issue for lack of detailed feedback.

**Closed as completed by limitedmage** 2012-05-11 07:10 UTC
