### ISSUE TITLE
Duplicated contact after receiving message

### ISSUE THREAD

**Issue by Kirioss** [lhchavez/gtalkchat#148] opened 2013-01-05 13:06 UTC
I received a message when the application was in background, and since, the contact of this person is now duplicated. Sign out / sign in solve the problem

**Comment by limitedmage** [comment] 2013-01-05 17:13
Duplicate of https://github.com/gchatapp/gtalkchat/issues/3

**Closed as completed by limitedmage** 2013-01-05 17:13 UTC
