### ISSUE TITLE
Go offline without log out

### ISSUE THREAD

**Issue by mersadk** [lhchavez/gtalkchat#107] opened 2012-03-14 00:32 UTC
I would like to be able to go offline without logging out so I don't have to enter mail and password each time a want to switch to online.

Otherwise great app :)

**Comment by vanquish83** [comment] 2012-03-15 23:44
I think that Project is no longer supported by authors.
There are many request of bugfixes and new feature but in 3 months no word about authors.

**Comment by lhchavez** [comment] 2012-04-16 02:58
I'll implement invisible instead of offline.

**Comment by lhchavez** [comment] 2012-04-16 02:58
This is a dupe of #84.

**Comment by limitedmage** [comment] 2012-04-16 02:58
This is basically a dupe of #84, so closing this one

**Closed as completed** 2012-04-16 02:58 UTC
